In [4]:
import fastf1

fastf1.Cache.enable_cache('cache')  # Enable caching to speed up data retrieval

fastf1.get_event_schedule(2024).head()  # Get the event schedule for the year 2024

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Sakhir,FORMULA 1 ARAMCO PRE-SEASON TESTING 2024,2024-02-23,Pre-Season Testing,testing,Practice 1,2024-02-21 10:00:00+03:00,2024-02-21 07:00:00,...,Practice 3,2024-02-23 10:00:00+03:00,2024-02-23 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,1,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024,2024-03-02,Bahrain Grand Prix,conventional,Practice 1,2024-02-29 14:30:00+03:00,2024-02-29 11:30:00,...,Practice 3,2024-03-01 15:30:00+03:00,2024-03-01 12:30:00,Qualifying,2024-03-01 19:00:00+03:00,2024-03-01 16:00:00,Race,2024-03-02 18:00:00+03:00,2024-03-02 15:00:00,True
2,2,Saudi Arabia,Jeddah,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2024,2024-03-09,Saudi Arabian Grand Prix,conventional,Practice 1,2024-03-07 16:30:00+03:00,2024-03-07 13:30:00,...,Practice 3,2024-03-08 16:30:00+03:00,2024-03-08 13:30:00,Qualifying,2024-03-08 20:00:00+03:00,2024-03-08 17:00:00,Race,2024-03-09 20:00:00+03:00,2024-03-09 17:00:00,True
3,3,Australia,Melbourne,FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2024,2024-03-24,Australian Grand Prix,conventional,Practice 1,2024-03-22 12:30:00+11:00,2024-03-22 01:30:00,...,Practice 3,2024-03-23 12:30:00+11:00,2024-03-23 01:30:00,Qualifying,2024-03-23 16:00:00+11:00,2024-03-23 05:00:00,Race,2024-03-24 15:00:00+11:00,2024-03-24 04:00:00,True
4,4,Japan,Suzuka,FORMULA 1 MSC CRUISES JAPANESE GRAND PRIX 2024,2024-04-07,Japanese Grand Prix,conventional,Practice 1,2024-04-05 11:30:00+09:00,2024-04-05 02:30:00,...,Practice 3,2024-04-06 11:30:00+09:00,2024-04-06 02:30:00,Qualifying,2024-04-06 15:00:00+09:00,2024-04-06 06:00:00,Race,2024-04-07 14:00:00+09:00,2024-04-07 05:00:00,True

In [2]:
session_1 =fastf1.get_session(2024, 'Bahrain', 'R')

session_1.load()  # Load the session data

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

In [17]:
session_1.laps.pick_drivers("VER").head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:01:37.489000,VER,1,0 days 00:01:37.284000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:41.266000,...,False,Red Bull Racing,0 days 00:59:59.911000,2024-03-02 15:03:42.342,12,1.0,False,,False,False
1,0 days 01:03:13.785000,VER,1,0 days 00:01:36.296000,2.0,1.0,NaT,NaT,0 days 00:00:30.916000,0 days 00:00:41.661000,...,False,Red Bull Racing,0 days 01:01:37.489000,2024-03-02 15:05:19.920,1,1.0,False,,False,True
2,0 days 01:04:50.538000,VER,1,0 days 00:01:36.753000,3.0,1.0,NaT,NaT,0 days 00:00:30.999000,0 days 00:00:41.966000,...,False,Red Bull Racing,0 days 01:03:13.785000,2024-03-02 15:06:56.216,1,1.0,False,,False,True
3,0 days 01:06:27.185000,VER,1,0 days 00:01:36.647000,4.0,1.0,NaT,NaT,0 days 00:00:30.931000,0 days 00:00:41.892000,...,False,Red Bull Racing,0 days 01:04:50.538000,2024-03-02 15:08:32.969,1,1.0,False,,False,True
4,0 days 01:08:04.358000,VER,1,0 days 00:01:37.173000,5.0,1.0,NaT,NaT,0 days 00:00:31.255000,0 days 00:00:42.056000,...,False,Red Bull Racing,0 days 01:06:27.185000,2024-03-02 15:10:09.616,1,1.0,False,,False,True

In [13]:
session_1.get_circuit_info()

CircuitInfo(corners=              X            Y  Number Letter       Angle     Distance
0     42.405939  8329.202564       1        -246.615311   712.268687
1    820.781621  7879.043841       2        -101.177469   811.756597
2   1912.969997  8065.442167       3        -261.394562   921.326499
3   7487.745293  6790.710716       4        -349.599066  1499.823600
4   5820.228443  4860.740936       5        -211.501597  1767.802411
5   5180.404121  4214.598861       6         -76.374442  1833.883491
6   4276.202937  4156.240631       7        -258.953372  1967.359346
7   2490.099011  2458.600397       8        -114.654309  2211.701734
8   2711.155288  5950.242339       9        -344.907956  2574.533764
9   2100.132716  6613.999851      10        -270.022000  2664.840818
10  2120.985221  -663.995072      11        -100.999671  3451.803025
11  4981.251162  1603.747622      12        -272.812824  3851.041887
12  6665.934072   449.275637      13        -358.727848  4060.756944
13  -145.412458 -3472.808548      14        -110.521532  4870.300202
14  -552.812606 -2803.666251      15        -169.061999  4953.332625, marshal_lights=              X            Y  Number Letter       Angle     Distance
0   -403.030010   819.261165       1        -182.636711  5306.336041
1   -170.997780  6888.075335       2        -181.620516   544.230065
2   2091.793058  8069.873588       3         -92.041958   921.326499
3   6028.332908  7353.740540       4        -280.465995  1340.530448
4   6384.228520  5548.195861       5        -229.171805  1686.876766
5   5401.364201  4328.365401       6         -58.412958  1833.883491
6   3886.937743  3990.070522       7        -238.912453  1994.491729
7   2977.381909  2780.529066       8         -35.812902  2152.956797
8   2422.170415  3733.439625       9        -192.417668  2349.567761
9   2747.081713  5711.158082      10        -353.833280  2555.116190
10  1949.470102  6521.582003      11        -214.748968  2688.642182
11  1520.829900   383.508904      12        -181.786865  3314.944921
12  3059.362995  -227.622315      13         -40.069301  3560.338721
13  3622.008522   852.958900      14        -205.613508  3668.262801
14  6222.549044  1091.238431      15        -297.156773  3979.170739
15  5396.067391  -632.096263      16         -63.183423  4234.367654
16  1241.794398 -2937.044985      17         -61.130134  4722.898020
17  -565.125813 -2116.921434      18        -182.793522  5030.330634, marshal_sectors=              X            Y  Number Letter       Angle     Distance
0   -393.185167  1019.245720       1        -183.019352  5323.435195
1   -175.143181  6721.273251       2        -181.661190   544.230065
2   2029.269964  8072.488919       3         -92.263093   921.326499
3   5938.043810  7370.224849       4        -280.364943  1335.767454
4   6513.700757  5653.428140       5        -232.068722  1673.044735
5   5440.095703  4352.899291       6         -48.640796  1833.883491
6   3821.952450  3945.006672       7        -231.591606  2014.695859
7   2911.010730  2694.768477       8         -39.203254  2166.963024
8   2442.776275  3827.134558       9        -191.015371  2365.092028
9   2738.529117  5781.550811      10        -352.998227  2555.116190
10  1949.477533  6521.591324      11        -212.616743  2688.642182
11  1517.999905   158.359360      12        -179.828461  3342.739442
12  3148.505677  -112.147992      13         -34.684526  3575.207549
13  3614.774870   837.916300      14        -205.638861  3668.262801
14  6110.804921  1147.597626      15        -296.589707  3979.170739
15  5307.278700  -678.311417      16         -61.886217  4234.367654
16  1046.005570 -3048.425352      17         -60.882073  4747.361912
17  -564.909333 -2112.755204      18        -183.198163  5030.330634, rotation=92.0)

In [3]:
import pyarrow # GOING FOR STABLE 22.0.0
import pandas as pd

df = pd.DataFrame(session_1.laps)
df.to_parquet('laps.parquet')